# Generated by Django 5.0.3 on 2024-10-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ProfilePicture',
            field=models.ImageField(upload_to='profile_pictures/'),
        ),
    ]
